# syntax version.
version: "3.5"

services:
  # swoole image
  alpine-swoole:
    container_name: alpine-swoole
    image: "hyperf/hyperf:8.0-alpine-v3.16-swoole-4.5.9"
    links:
      - mongo
    ports:
      - "8001:9501"
    build:
      context: "."
      args:
        ALPINE_VERSION: 3.16
        SW_VERSION: 4.5.9
        COMPOSER_VERSION: 2.5.8
        PHP_BUILD_VERSION: 8.0
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  mongo:
    container_name: wb-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongodbdata:/data/db
    networks:
      - app-network

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    links:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge